# -----------------------------------------------------------------------------=
# $Id: Makefile,v 1.1 2000/02/28 17:06:26 simonmar Exp $
#
# (c) The GHC Team, 2000
#

TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = DrIFT DtdToHaskell Xtract

include $(TOP)/mk/target.mk
