# -----------------------------------------------------------------------------=
# $Id: Makefile,v 1.1.2.1 2000/06/29 11:24:30 rrt Exp $
#
# (c) The GHC Team 1997-1999
#

TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = src

include $(TOP)/mk/target.mk
